import test from 'node:test';
import assert from 'node:assert/strict';
import {QUESTIONS,UPGRADES} from '../src/content.mjs';
import {createState,transition,rewards,economy,canRetry,canBuy,encodeCheckpoint,decodeCheckpoint,restoreProgress,readCheckpoint,saveCheckpoint,MAX_EARNED,MAX_BASE_REVISION} from '../src/model.mjs';
const act=(s,type,other={})=>transition(s,{type,expectedRevision:s.revision,...other});
function perfect(s=createState()) {s=act(s,'START');const q=QUESTIONS[s.index];s=act(s,'SUBMIT',{choice:q.answer,reason:q.reason});return act(s,'REVIEW');}
function allPerfect(){let s=createState();for(let i=0;i<QUESTIONS.length;i++){s=perfect(s);s=act(s,'NEXT');}return s;}
test('first attempt separately rewards answer, reasoning and review',()=>{let s=act(createState(),'START');s=act(s,'SUBMIT',{choice:0,reason:1});assert.deepEqual(economy(s),{earned:8,spent:0,available:8});s=act(s,'REVIEW');assert.deepEqual(rewards(s.records[0],QUESTIONS[0]),{answer:4,reasoning:4,review:2,total:10});});
test('duplicate, retained and changed-choice answer callbacks cannot award twice',()=>{let s=act(createState(),'START');const event={type:'SUBMIT',expectedRevision:s.revision,choice:0,reason:1};s=transition(s,event);assert.equal(transition(s,event),s);assert.equal(transition(s,{...event,choice:1}),s);assert.equal(act(s,'SUBMIT',{choice:0,reason:1}),s);assert.equal(economy(s).earned,8);});
test('retry rewards only newly corrected parts, and cannot loop',()=>{let s=act(createState(),'START');s=act(s,'SUBMIT',{choice:1,reason:0});assert.equal(economy(s).earned,0);assert.equal(canRetry(s),true);s=act(s,'RETRY');s=act(s,'SUBMIT',{choice:0,reason:1});assert.equal(economy(s).earned,4);assert.equal(canRetry(s),false);assert.equal(act(s,'RETRY'),s);s=act(s,'REVIEW');assert.equal(economy(s).earned,6);assert.equal(act(s,'REVIEW'),s);});
test('correct reasoning is worth as much as a correct answer',()=>{let s=act(createState(),'START');s=act(s,'SUBMIT',{choice:1,reason:1});assert.equal(economy(s).earned,4);s=act(s,'RETRY');s=act(s,'SUBMIT',{choice:0,reason:1});assert.equal(economy(s).earned,6);s=act(s,'REVIEW');assert.equal(economy(s).earned,8);});
test('retry cannot lose already earned parts or pay for them again',()=>{let s=act(createState(),'START');s=act(s,'SUBMIT',{choice:0,reason:0});s=act(s,'RETRY');s=act(s,'SUBMIT',{choice:1,reason:1});assert.deepEqual(rewards(s.records[0],QUESTIONS[0]),{answer:4,reasoning:2,review:0,total:6});});
test('no retry after fully correct work; no repeated review or skipped phases',()=>{let s=createState();for(const type of ['SUBMIT','RETRY','REVIEW','NEXT','BUY'])assert.equal(act(s,type,{choice:0,reason:1,id:'notebook'}),s);s=act(s,'START');s=act(s,'SUBMIT',{choice:0,reason:1});assert.equal(canRetry(s),false);assert.equal(act(s,'NEXT'),s);s=act(s,'REVIEW');assert.equal(act(s,'REVIEW'),s);});
test('upgrade eligibility enforces funds, phase, known item and one-time purchases',()=>{let s=perfect();assert.equal(canBuy(s,'notebook'),true);assert.equal(canBuy(s,'bath'),false);assert.equal(act(s,'BUY',{id:'bath'}),s);assert.equal(act(s,'BUY',{id:'unknown'}),s);const stale={type:'BUY',expectedRevision:s.revision,id:'notebook'};s=transition(s,stale);assert.equal(economy(s).available,4);assert.equal(economy(s).spent,6);assert.equal(transition(s,stale),s);assert.equal(act(s,'BUY',{id:'notebook'}),s);s=act(s,'NEXT');assert.equal(act(s,'BUY',{id:'notebook'}),s);});
test('full run has a strict 120 ceiling and terminal actions do not farm currency',()=>{let s=allPerfect();assert.equal(s.phase,'complete');assert.equal(economy(s).earned,120);assert.equal(MAX_EARNED,120);for(let i=0;i<100;i++)for(const type of ['NEXT','REVIEW','SUBMIT','BUY','RETRY','START'])assert.equal(act(s,type,{choice:0,reason:1,id:'notebook'}),s);});
test('equipment never changes rewards and all equipment is reachable',()=>{let s=createState();for(let i=0;i<QUESTIONS.length;i++){s=perfect(s);for(const u of UPGRADES)if(canBuy(s,u.id))s=act(s,'BUY',{id:u.id});s=act(s,'NEXT');}assert.equal(s.owned.length,4);assert.deepEqual(economy(s),{earned:120,spent:60,available:60});});
test('invalid or missing input never changes state',()=>{const s=act(createState(),'START');for(const choice of [-1,4,NaN,Infinity,0.5,null,undefined,'0'])assert.equal(act(s,'SUBMIT',{choice,reason:1}),s);for(const reason of [-1,3,NaN,null,'1'])assert.equal(act(s,'SUBMIT',{choice:0,reason}),s);assert.equal(transition(s,null),s);assert.equal(transition(s,{type:'SUBMIT',choice:0,reason:1}),s);});
test('checkpoint replays deterministically without trusting score fields',()=>{let s=perfect();s=act(s,'BUY',{id:'notebook'});const encoded=encodeCheckpoint(s);assert.deepEqual(decodeCheckpoint(encoded).state,s);const changed=JSON.parse(encoded);changed.earned=10000000;assert.equal(economy(decodeCheckpoint(JSON.stringify(changed)).state).earned,10);});
test('checkpoint rejects corrupt, stale-content, impossible, oversized, duplicate and reset events',()=>{for(const raw of ['',null,'{bad','x'.repeat(50001)])assert.equal(decodeCheckpoint(raw).state,null);const original=JSON.parse(encodeCheckpoint(perfect()));for(const modify of [d=>d.version=5,d=>d.contentRevision='foreign',d=>d.baseRevision=-1,d=>d.events.push(d.events[0]),d=>d.events[0].type='BUY',d=>d.events[0].type='RESET',d=>d.events[1].choice=99,d=>d.events=Array(101).fill({})]){const d=structuredClone(original);modify(d);assert.equal(decodeCheckpoint(JSON.stringify(d)).state,null);}});
test('checkpoint survives every phase including retry and completion',()=>{let s=createState();const check=()=>assert.deepEqual(decodeCheckpoint(encodeCheckpoint(s)).state,s);check();s=act(s,'START');check();s=act(s,'SUBMIT',{choice:1,reason:0});check();s=act(s,'RETRY');check();s=act(s,'SUBMIT',{choice:0,reason:1});check();s=act(s,'REVIEW');check();s=act(s,'BUY',{id:'notebook'});check();s=act(s,'NEXT');check();s=allPerfect();check();});
test('reset and undo use fresh callback ownership',()=>{const old=perfect();const stale={type:'BUY',expectedRevision:old.revision,id:'notebook'};const reset=act(old,'RESET');assert.deepEqual(economy(reset),{earned:0,spent:0,available:0});assert.equal(reset.phase,'learn');assert.equal(old.records[0].reviewed,true);assert.equal(transition(reset,stale),reset);const undo=restoreProgress(reset,old);assert.equal(economy(undo).earned,10);assert.deepEqual(undo.records,old.records);assert.equal(transition(undo,stale),undo);assert.deepEqual(decodeCheckpoint(encodeCheckpoint(undo)).state,undo);});
test('storage errors are explicit and reads do not overwrite',()=>{let writes=0;const storage={getItem:()=>'{invalid',setItem:()=>{writes++;throw new Error('quota');}};assert.ok(readCheckpoint(storage).error);assert.equal(writes,0);assert.ok(saveCheckpoint(storage,createState()));assert.ok(readCheckpoint(null).error);assert.deepEqual(readCheckpoint({getItem:()=>null}),{state:null,error:null});});
test('all answer and reason combinations have bounded transparent scores',()=>{for(const q of QUESTIONS)for(let a=0;a<4;a++)for(let b=0;b<3;b++)for(let c=0;c<4;c++)for(let d=0;d<3;d++){const r={attempts:[{choice:a,reason:b},{choice:c,reason:d}],reviewed:true};const x=rewards(r,q);assert.ok(x.total>=2&&x.total<=10);assert.equal(x.total,x.answer+x.reasoning+x.review);}});

test('checkpoint counters reject unsafe values and reserve exact arithmetic headroom',()=>{
 for(const baseRevision of [Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER-1,MAX_BASE_REVISION+1,1.5,-1,Infinity,NaN]){
  assert.throws(()=>createState(baseRevision),RangeError);
  const raw=JSON.stringify({...JSON.parse(encodeCheckpoint(createState())),baseRevision});
  assert.equal(decodeCheckpoint(raw).state,null);
 }
 let s=createState(MAX_BASE_REVISION);const previous=s.revision;s=act(s,'START');assert.equal(s.revision,previous+1);assert.ok(Number.isSafeInteger(s.revision));assert.deepEqual(decodeCheckpoint(encodeCheckpoint(s)).state,s);
});
test('maximum supported checkpoint cannot stall revisions or accept an old review',()=>{
 let s=perfect(createState(MAX_BASE_REVISION));const stale={type:'REVIEW',expectedRevision:s.revision-1};s=act(s,'NEXT');s=act(s,'START');s=act(s,'SUBMIT',{choice:2,reason:2});
 assert.equal(transition(s,stale),s);assert.equal(s.records[1].reviewed,false);s=act(s,'REVIEW');assert.equal(economy(s).earned,20);
 assert.deepEqual(decodeCheckpoint(encodeCheckpoint(s)).state,s);
});
test('reset and restore fail closed when rebasing exceeds the supported bound',()=>{
 const edge=perfect(createState(MAX_BASE_REVISION));assert.equal(act(edge,'RESET'),edge);assert.equal(restoreProgress(edge,perfect()),edge);assert.deepEqual(decodeCheckpoint(encodeCheckpoint(edge)).state,edge);
 const near=createState(MAX_BASE_REVISION-1);const reset=act(near,'RESET');assert.equal(reset.baseRevision,MAX_BASE_REVISION);assert.deepEqual(decodeCheckpoint(encodeCheckpoint(reset)).state,reset);assert.equal(act(reset,'RESET'),reset);
});
test('reset rejects invalid clocks and restore rejects invalid saved action sequences',()=>{
 const good=perfect();for(const revision of [NaN,Infinity,Number.MAX_SAFE_INTEGER,good.revision+1]){const bad={...good,revision};assert.equal(transition(bad,{type:'RESET',expectedRevision:revision}),bad);assert.equal(restoreProgress(bad,good),bad);}
 const current=createState();for(const saved of [null,{}, {...good,baseRevision:Number.MAX_SAFE_INTEGER},{...good,events:[{type:'REVIEW',expectedRevision:0}]}])assert.equal(restoreProgress(current,saved),current);
});
