// Original sample items. Scope: selected equilibrium fundamentals in NSW Chemistry
// Stage 6 (2017), Year 12 Module 5. Not an official paper or complete module bank.
export const CONTENT_REVISION = 'equilibrium-sample-2026-10-04-v1';
export const SCOPE = 'Year 12 Chemistry · Module 5 · Equilibrium fundamentals';
export const QUESTIONS = [
  {
    id: 'dynamic', title: 'A busy balance', topic: 'Dynamic equilibrium',
    learn: 'A reversible reaction can keep changing at particle level while the bulk mixture looks unchanged. Compare rates, not just amounts.',
    equation: 'reactants ⇌ products',
    stem: 'A sealed reacting mixture has reached dynamic equilibrium at constant temperature. Which statement must be true?',
    answers: ['The forward and reverse reaction rates are equal.', 'The reactant and product concentrations are equal.', 'Both reactions have stopped.', 'All reactants have become products.'], answer: 0,
    reasons: ['Equal concentrations are necessary for equal rates.', 'Particles still react in both directions, with no net change in composition.', 'A sealed vessel prevents every chemical reaction.'], reason: 1,
    explanation: 'Dynamic means both reactions continue. Equal opposing rates keep each concentration steady; the concentrations need not equal one another. Stopping and complete conversion are different ideas.',
  },
  {
    id: 'closed', title: 'Keep the system together', topic: 'Closed systems',
    learn: 'Matter escaping can keep changing a mixture. A closed system prevents that exchange; it can still exchange energy with its surroundings.',
    equation: 'N₂O₄(g) ⇌ 2NO₂(g)',
    stem: 'Which setup best allows this gas mixture to establish equilibrium at a controlled temperature, given enough time?',
    answers: ['An open flask with gas continuously escaping.', 'A vessel from which NO₂ is continuously removed.', 'A sealed vessel maintained at constant temperature.', 'A sealed vessel must be at equilibrium immediately.'], answer: 2,
    reasons: ['Sealing guarantees instant equality of concentrations.', 'A constant temperature stops all molecular collisions.', 'Retaining the gases allows both directions to continue without ongoing material loss.'], reason: 2,
    explanation: 'A sealed, temperature-controlled vessel retains the reacting gases. The system still needs time to equilibrate. Open loss or continuous product removal disturbs the composition; sealing alone does not establish equilibrium instantly.',
  },
  {
    id: 'add-reactant', title: 'A fresh supply', topic: 'Concentration changes',
    learn: 'After a concentration disturbance, consider which net reaction consumes some of the added species. Temperature and volume stay fixed in this challenge.',
    equation: 'H₂(g) + I₂(g) ⇌ 2HI(g)',
    stem: 'H₂ is added to an equilibrium mixture at constant temperature and volume. Which net reaction occurs as equilibrium is re-established?',
    answers: ['A net reverse reaction forms more H₂.', 'A net forward reaction forms more HI.', 'No change, because equilibrium can never be disturbed.', 'The equilibrium constant increases.'], answer: 1,
    reasons: ['The forward reaction consumes some of the added H₂.', 'Adding any gas always favours the side with fewer molecules.', 'The system removes every added H₂ molecule.'], reason: 0,
    explanation: 'Adding H₂ lowers Qc for this equation below Kc. A net forward reaction consumes some H₂ and I₂ and forms HI until Qc = Kc again. The added H₂ is not necessarily used up; Kc is unchanged at this temperature.',
  },
  {
    id: 'compression', title: 'Room to react', topic: 'Gas pressure and volume',
    learn: 'For an ideal-gas equilibrium, a volume decrease at constant temperature favours the side with fewer moles of gas, when the two sides differ.',
    equation: '2SO₂(g) + O₂(g) ⇌ 2SO₃(g)',
    stem: 'The vessel is compressed at constant temperature. In which direction does the equilibrium composition shift?',
    answers: ['Left, towards three moles of gas.', 'Neither way, because temperature is fixed.', 'It depends only on which side has heavier molecules.', 'Right, towards two moles of gas.'], answer: 3,
    reasons: ['Compression changes the balanced coefficients.', 'The forward reaction reduces the total number of gas particles.', 'Pressure only affects reaction speed and never composition.'], reason: 1,
    explanation: 'The left side has three gas moles per reaction as written; the right has two. Compression favours net forward reaction. A fixed temperature keeps Kc unchanged, but the equilibrium composition can still change.',
  },
  {
    id: 'equal-gas', title: 'A useful exception', topic: 'Equal gas-mole totals',
    learn: 'Count all gas coefficients on each side before predicting a pressure effect. Assume ideal gases here.',
    equation: 'H₂(g) + I₂(g) ⇌ 2HI(g)',
    stem: 'An equilibrium mixture is compressed at constant temperature. What happens to its equilibrium mole proportions?',
    answers: ['They remain unchanged.', 'They shift entirely to HI.', 'They shift towards H₂ and I₂.', 'They become equal for all three gases.'], answer: 0,
    reasons: ['Compression has no effect on any gas concentration.', 'The gas molecules stop colliding after compression.', 'Both sides have two gas moles, so uniform compression leaves Qc unchanged.'], reason: 2,
    explanation: 'All concentrations rise immediately, but [HI]² and [H₂][I₂] scale by the same factor. Qc remains Kc, so there is no net composition shift under the ideal-gas model. Unchanged mole proportions do not mean unchanged concentrations.',
  },
  {
    id: 'temperature', title: 'Warm the model', topic: 'Temperature changes',
    learn: 'Identify the endothermic direction before predicting a temperature effect. This is a conceptual model, not an instruction to heat real chemicals.',
    equation: 'N₂O₄(g) ⇌ 2NO₂(g)    ΔH > 0 (forward)',
    stem: 'This equilibrium mixture is heated. Which prediction is correct for the equilibrium position and Kc?',
    answers: ['It shifts left and Kc decreases.', 'It shifts right and Kc increases.', 'It shifts right while Kc must stay constant.', 'It does not shift because the vessel is sealed.'], answer: 1,
    reasons: ['Heating favours every forward reaction, regardless of ΔH.', 'A sealed system cannot exchange energy.', 'Higher temperature favours the endothermic direction, which is forward here.'], reason: 2,
    explanation: 'The forward reaction is endothermic, so heating favours NO₂ formation and increases Kc. Temperature can change Kc; concentration, volume and a catalyst at the same temperature do not.',
  },
  {
    id: 'catalyst', title: 'Faster, same destination', topic: 'Catalysts',
    learn: 'A catalyst changes the pathway and helps both reaction directions. Keep the distinction between rate and equilibrium composition in mind.',
    equation: 'reversible reaction + suitable catalyst',
    stem: 'A suitable catalyst is added to a mixture already at equilibrium, with temperature unchanged. What is the expected effect?',
    answers: ['Kc becomes larger.', 'Only the forward reaction becomes faster.', 'The equilibrium composition stays the same.', 'The reaction goes to completion.'], answer: 2,
    reasons: ['Both directions are accelerated without changing Kc.', 'A catalyst permanently supplies extra product.', 'The reverse reaction is completely blocked.'], reason: 0,
    explanation: 'A catalyst accelerates both opposing reactions. It can shorten the time to reach equilibrium from a non-equilibrium mixture, but it does not alter Kc or the equilibrium composition at fixed temperature.',
  },
  {
    id: 'expression', title: 'Write the balance', topic: 'Equilibrium expressions',
    learn: 'In the concentration expression, use products over reactants and raise each concentration to its balanced coefficient. Square brackets mean concentration.',
    equation: 'N₂(g) + 3H₂(g) ⇌ 2NH₃(g)',
    stem: 'Which is the correct Kc expression for this equation?',
    answers: ['[N₂][H₂]³ / [NH₃]²', '[NH₃] / ([N₂][H₂])', '2[NH₃] / (3[N₂][H₂])', '[NH₃]² / ([N₂][H₂]³)'], answer: 3,
    reasons: ['Coefficients multiply concentrations outside brackets.', 'Balanced coefficients become powers in the products-over-reactants expression.', 'Every species always has power one.'], reason: 1,
    explanation: 'NH₃ is the product and has coefficient 2, so [NH₃]² is the numerator. N₂ has coefficient 1 and H₂ has coefficient 3, giving [N₂][H₂]³ in the denominator. Coefficients are powers, not prefactors.',
  },
  {
    id: 'calculate', title: 'A small calculation', topic: 'Calculating Kc',
    learn: 'Use equilibrium concentrations, not starting concentrations. For this equation the concentration units cancel in the ratio.',
    equation: 'H₂(g) + I₂(g) ⇌ 2HI(g)',
    stem: 'At equilibrium, [HI] = 0.40 mol L⁻¹, [H₂] = 0.20 mol L⁻¹ and [I₂] = 0.20 mol L⁻¹. What is Kc?',
    answers: ['4.0', '1.0', '0.25', '10'], answer: 0,
    reasons: ['Use 0.40 ÷ (0.20 × 0.20).', 'Use (0.20 × 0.20) ÷ 0.40².', 'Use 0.40² ÷ (0.20 × 0.20).'], reason: 2,
    explanation: 'Kc = [HI]² / ([H₂][I₂]) = 0.16 / 0.04 = 4.0. The 10 distractor leaves HI unsquared, while 0.25 reverses the ratio. This calculation says nothing about how quickly equilibrium was reached.',
  },
  {
    id: 'quotient', title: 'Which way next?', topic: 'Comparing Qc and Kc',
    learn: 'Qc uses the current mixture and Kc describes equilibrium at that temperature. Comparing them predicts the net reaction direction.',
    equation: 'A(g) ⇌ B(g)    Qc = [B]/[A]',
    stem: 'For this model reaction at a fixed temperature, Qc = 0.50 and Kc = 2.0. What happens as equilibrium is approached?',
    answers: ['A net reverse reaction makes more A.', 'A net forward reaction makes more B.', 'No net reaction, because Qc is positive.', 'Kc falls until it equals the initial Qc.'], answer: 1,
    reasons: ['Qc < Kc, so the product-to-reactant ratio must rise.', 'A smaller Qc means the mixture already contains too much product.', 'Kc changes whenever concentrations change.'], reason: 0,
    explanation: 'Qc is smaller than Kc, so there is too little B relative to A for equilibrium at this temperature. Net forward reaction raises [B]/[A] until Qc reaches 2.0. Kc does not move to meet the initial Qc.',
  },
  {
    id: 'solid', title: 'The solid stays out', topic: 'Heterogeneous equilibrium',
    learn: 'Pure solids have effectively constant activity and are omitted from this school-level equilibrium expression. Both solid phases must remain present.',
    equation: 'CaCO₃(s) ⇌ CaO(s) + CO₂(g)',
    stem: 'At fixed temperature and volume, more pure CaCO₃ is added to a mixture at equilibrium while both solids remain present. What happens to equilibrium CO₂ concentration?',
    answers: ['It doubles for every doubling of solid mass.', 'It falls to zero.', 'It remains unchanged.', 'It must rise because a reactant was added.'], answer: 2,
    reasons: ['Pure solids are included using their masses in Kc.', 'For this system, the simplified expression is Kc = [CO₂].', 'The solid cannot take part in the reaction.'], reason: 1,
    explanation: 'With both pure solid phases present, the simplified Kc expression contains only [CO₂]. At unchanged temperature, Kc is fixed, so adding more pure solid does not change the equilibrium gas concentration. Solids do react; omission does not mean inactivity.',
  },
  {
    id: 'constant', title: 'The final control', topic: 'What changes Kc?',
    learn: 'A new equilibrium composition does not always mean a new equilibrium constant. Keep the reaction equation unchanged for this comparison.',
    equation: 'same reaction equation · equilibrium constant Kc',
    stem: 'For the same reaction as written, which change can alter Kc?',
    answers: ['Adding more reactant at fixed temperature.', 'Compressing an ideal-gas mixture at fixed temperature.', 'Adding a suitable catalyst at fixed temperature.', 'Changing the temperature.'], answer: 3,
    reasons: ['Any change that shifts composition changes Kc.', 'Kc is a measure of reaction speed.', 'Kc depends on temperature for a specified reaction.'], reason: 2,
    explanation: 'Changing temperature can change Kc for the same reaction. Concentration or pressure changes may alter equilibrium composition while preserving Kc at that temperature. A catalyst affects rate rather than Kc. Reversing or rescaling the equation would also change the expression, but is excluded here.',
  },
];
export const UPGRADES = [
  {id:'notebook', name:'Field notebook', cost:6, mark:'01', description:'Add a permanent concept card to your bench.', note:'Rates can be equal while concentrations are different. Read the quantity named in the question.'},
  {id:'bath', name:'Temperature station', cost:12, mark:'02', description:'Equip a model temperature-control station.', note:'A temperature change can alter Kc. A concentration change at fixed temperature does not.'},
  {id:'sensor', name:'Gas sensor', cost:18, mark:'03', description:'Add a gas-ratio display to your bench.', note:'For compression questions, count only gas coefficients. Equal gas-mole totals give no ideal-gas shift.'},
  {id:'console', name:'Analysis console', cost:24, mark:'04', description:'Complete your bench with an equation console.', note:'Write the balanced equation first, then use products over reactants with coefficients as powers.'},
];
